# Generated by Django 6.0.4 on 2026-05-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đơn đặt tour',
                'verbose_name_plural': 'Các đơn đặt tour',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='VNPay', max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('transaction_code', models.CharField(blank=True, max_length=255, null=True)),
                ('vnp_txn_ref', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creator_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('admin_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('content', models.TextField(verbose_name='Nội dung đánh giá')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Các đánh giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Việt Nam', max_length=255)),
                ('title', models.CharField(max_length=255, verbose_name='Tên Tour')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Ngày khởi hành')),
                ('slots', models.IntegerField(verbose_name='Số chỗ')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link ảnh')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Vĩ độ (Lat)')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Kinh độ (Lng)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Chuyến du lịch',
                'verbose_name_plural': 'Các chuyến du lịch',
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images/', verbose_name='Ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnp_txn_ref', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_info', models.TextField()),
                ('vnp_response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('vnp_transaction_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
