# Generated by Django 6.0.4 on 2026-04-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày khởi hành'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link ảnh'),
        ),
    ]
