# Generated by Django 6.0.5 on 2026-05-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ thanh toán"),
                    ("confirmed", "Đã xác nhận"),
                    ("cancelled", "Đã hủy"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
