# Generated by Django 5.2.13 on 2026-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_departure_date_tour_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
