# Generated by Django 5.2.13 on 2026-04-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tour_id'),
        ('tours', '0005_tourimage'),
    ]

    operations = [
    ]
