# Generated by Django 5.2.13 on 2026-04-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_merge_0005_alter_tour_id_0005_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ (Lat)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ (Lng)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
