# Generated by Django 6.0.4 on 2026-04-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PROVIDER', 'Provider'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
